### ISSUE TITLE
Single file no more?

### ISSUE THREAD

**Issue by bjornbm** [philanc/ple#3]
Sweet project!

From the [plterm README](https://github.com/philanc/plterm/blob/master/README.md) (emphasis mine):

> This module was initially developed for [PLE](https://github.com/philanc/ple), my "Pure Lua text Editor". **It is embedded at the beginning og PLE, so that the editor can be delivered as a single Lua file**.

This seems to no longer be the case though, with `plterm.lua` and `buffer.lua` being separate files. Do you confirm? (Or due you have a method of merging them into one file?)

**Comment by philanc** [comment]
You are perfectly right. I will go back to delivering ple as one Lua file.  I don't know yet if I will merge buffer and term back into ple, or keep the modular structure. In the latter case, I will provide a small Lua script to build the "one-file" editor from the components.

Thanks for the nudge!

Phil

**Comment by philanc** [comment]
I have added `make_ple.lua`, a Lua script that combines `ple.lua` and the modules it uses into a one-file editor script `ple`.  Just run it in the project directory:

`lua make_ple.lua`

It produces a standalone Lua script `ple` that can be used anywhere.  `ple` is prefixed with `#!/bin/env lua` and made executable so it can be directly invoked from the command line:

`$  ple  [filename]`

**Comment by bjornbm** [comment]
Works well! Only problem is that on the systems I have in front of me, macOS and Alpinelinux, `env` is only at `/usr/bin/env` and not at `/bin/env`. My impression from the internet is that `/usr/bin/env` is the more common location. On termux (linux on android) both paths work.

**Comment by philanc** [comment]
You are right. I'll fix it.

**Comment by bjornbm** [comment]
Fixed with 68eae0ec0c3f63f354d509feae6b8c72ab72c9df.

Works great, very convenient. Thanks!
